[package]
name = "vigenere_solver"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
license = "Apache-2.0"

[dependencies]
argparse = "0.2.1"
rustc-hex = "1.0.0"
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.0"
